#!/usr/bin/ruby
require File.join(File.dirname(__FILE__), '../config/boot')
require 'environment'

DebugLevel=5

def debug(level, text)
  puts '*'*(5-level) + ' ' + text if level <= DebugLevel
end

def start_instances(lab, howmany)
  howmany.times do |num|
    begin
      lab.start_instance
    rescue NoProfileAvailable
      debug 0, 'No default profiles available for this laboratory while ' +
        'starting instance (%d/%d)' % [num, howmany]
      return nil
    end
  end
end

Laboratory.find(:all).map do |lab|
  debug 3, 'Laboratory %d (%s)' % [lab.id, lab.name]

  should_have = lab.start_instances
  active = lab.active_instances.size
  instances = should_have - active
  instances = 0 if instances < 0

  debug 5, 'Attempting to start %d instances (%d already active, %d wanted)' % 
    [instances, active, should_have]
  start_instances(lab, instances)

  # Among the currently running instances for this laboratory, does
  # any require to be restarted?
  lab.active_instances.each do |inst|
    next unless inst.needs_restart?
    prof = inst.profile
    debug 5, ("Restarting instance %s (profile %s: %s)\n" +
              "    Restart every %d days; running since %s") %
      [inst.pid, prof.id, prof.name, prof.restart_freq, inst.startup_time]
    inst.stop
    sleep 1 # To insure all resources are freed
    prof.start_instance
  end
end
